module.exports = {
  docs: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Training',
      href: 'https://azurelocal.cloud/azurelocal-training/',
    },
  ],
};
