// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [
    { type: 'doc', id: 'index' },
    {
      type: 'category',
      label: 'Planning & Discovery',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'planning' }],
    },
    {
      type: 'category',
      label: 'Design',
      collapsed: true,
      collapsible: true,
      link: { type: 'generated-index', description: 'High-Level and Low-Level design documents for Azure Local deployments.' },
      items: [{ type: 'autogenerated', dirName: 'design' }],
    },
    {
      type: 'category',
      label: 'Implementation Guide',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'implementation' }],
    },
    {
      type: 'category',
      label: 'Automation Guide',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'automation' }],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
    {
      type: 'link',
      label: 'Training',
      href: 'https://azurelocal.cloud/azurelocal-training/',
    },
    {
      type: 'category',
      label: 'Azure Services on Azure Local',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'azure-services' }],
    },
    {
      type: 'category',
      label: 'Lab Environment',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'lab-environment' }],
    },
    { type: 'doc', id: 'reference' },
    {
      type: 'category',
      label: 'Standards',
      collapsed: true,
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'standards' }],
    },
  ],
};

export default sidebars;
