// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [
    { type: 'doc', id: 'index' },
    { type: 'autogenerated', dirName: 'planning' },
    { type: 'autogenerated', dirName: 'design' },
    { type: 'autogenerated', dirName: 'implementation' },
    { type: 'autogenerated', dirName: 'automation' },
    { type: 'autogenerated', dirName: 'operations' },
    { type: 'autogenerated', dirName: 'azure-services' },
    { type: 'autogenerated', dirName: 'lab-environment' },
    { type: 'doc', id: 'reference' },
    { type: 'autogenerated', dirName: 'standards' },
    {
      type: 'link',
      label: 'Training',
      href: 'https://azurelocal.cloud/azurelocal-training/',
    },
  ],
};

export default sidebars;
